name: Go

on: [ push ]

jobs:
  UI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./web/views
        run: npm i
      - name: Build
        working-directory: ./web/views
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: assets
          path: web/views/public
  Service:
    runs-on: ubuntu-latest
    needs:
      - UI
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: web/views/public
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test ./...
      - name: Build
        run: go build cmd/unterlagen.go
